jobs:
- template: build/tmpl/jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'

- template: build/tmpl/jobs.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'

- template: build/tmpl/jobs.yml
  parameters:
    name: Windows
    vmImage: 'windows-2019'
